# Generated by Django 5.2.4 on 2025-07-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryagainapp', '0003_alter_task_deadline_alter_task_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Important',
            field=models.CharField(choices=[('NI', 'Not important'), ('I', 'Important')], default='NI', max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='Deadline',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='Start',
            field=models.DateField(blank=True),
        ),
    ]
