# Generated by Django 5.2.4 on 2025-07-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryagainapp', '0004_task_important_alter_task_deadline_alter_task_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='Start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='Task_completed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
