# Generated by Django 5.2.4 on 2025-07-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryagainapp', '0005_alter_task_deadline_alter_task_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Important',
            field=models.CharField(choices=[('Not important', 'Not important'), ('Important', 'Important')], default='Not important', max_length=20),
        ),
    ]
